apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: infra-gitops-app
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    name: infra-gitops-repo
    repoURL: https://github.com/oysvendsen/infra
    path: argocd-manifests
    
    
