apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nginx-ingress-controller
spec:
  project: default
  source: 
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 2.2.2
  destination:
    name: "in-cluster"
    namespace: nginx-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
      prune: true